### ISSUE TITLE
Broken Link: Download of MERRA data via FTP not possible any longer

### ISSUE THREAD

**Issue by simnh** [tum-ens/pyGRETA#161]
Hey,

I was going through the documentation and found that the link for the MERRA2 weather data is not available any longer. 

```
Deprecation of the MERRA and MERRA-2 Unique Web Interface Subsetter 
```

It seems that now users need to use the Web API. Is there already a script as a  template available for the the download of required data? Otherwise I would probably write one which could be also added to the docs for example?

**Comment by kais-siala** [comment]
Hi Simon,

You are right.
For a quick solution, you can follow this link
https://disc.gsfc.nasa.gov/datasets?keywords=merra-2&page=1
And look for M2T1NXRAD and M2T1NXSLV.
Or click on these two links directly:
https://disc.gsfc.nasa.gov/datasets/M2T1NXRAD_5.12.4/summary?keywords=merra-2
https://disc.gsfc.nasa.gov/datasets/M2T1NXSLV_5.12.4/summary?keywords=merra-2

Then you have to select "Subset / Get data" on the right. In the "Download Method", click on "Get File Subsets using the GES DISC Subsetter". Then you can choose the variables needed in the script.

You could edit the documentation accordingly, or I can do it when I have some time :-)

Ideally there should be a script to download the data directly from the FTP server, but I haven't done that yet. Do you have any experience with that?

**Comment by simnh** [comment]
Thanks for the link, this seems to work for now. I did not use the FTP server. But I think the links are also fine to use.
