### ISSUE TITLE
Windatlas CSV Data for Corrrection

### ISSUE THREAD

**Issue by simnh** [tum-ens/pyGRETA#162]
Hey again,

inside the source code, "WindSpeed.csv" is used for and read [here](https://github.com/tum-ens/pyGRETA/blob/41d6cc62d40faa5c9c9666db1010ba9bc8c86540/code/lib/correction_functions.py#L213-L219). However, from the global wind atlas side, I only found gis (.tif) data to download. Could you state where to get the required csv-file?

**Comment by kais-siala** [comment]
Hi, I select the countries, set the height to 50m (on the map, bottom right corner, next to legend), then download "plot data". I only need the CSV file.

**Comment by simnh** [comment]
Ah nice, missed it! Thanks
