### ISSUE TITLE
New name for repo

### ISSUE THREAD

**Issue by kais-siala** [tum-ens/pyGRETA#87]
Any suggestions?
Apparently, I can rename it and users who search for the other link get redirected to the new one.

**Comment by HoussameH** [comment]
How about Ammon(, Amun, Amon)? Egyptian God of air and sun. AmmonPy sounds pretty good?

**Comment by kais-siala** [comment]
The problem with these deities is that they had many roles. I do not connect Amun to both wind and sun.
And they had multiple gods for the Sun in Ancient Egypt...

**Comment by kais-siala** [comment]
I was about to suggest PyPOTS
(potential + time series)
but there is a library called PyPot
